# Generated by Django 2.2.7 on 2019-11-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_admin', '0004_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2',
            name='status',
        ),
    ]
