# Generated by Django 2.2.7 on 2019-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_admin', '0005_remove_user2_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_tiem',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
