# Generated by Django 2.2.7 on 2019-11-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_admin', '0006_auto_20191123_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'username')},
        ),
    ]
